### ISSUE TITLE
AS Circular 500-weight font does not load

### ISSUE THREAD

**Issue by MattSidor** [AlaskaAirlines/WebCoreStyleSheets#87]
## Describe the bug
The required font file for 500-weight AS Circular does not appear to load in projects which import `"~@alaskaairux/webcorestylesheets/dist/fonts"` and specify a style rule of `font-weight: var(--auro-text-heading-default-weight)`.

## To Reproduce
1. Load a project which imports the webcorestylesheets `fonts.scss` file (and all other necessary webcorestylesheets / design tokens) and defines an element with `font-weight: var(--auro-text-heading-default-weight)` or `font-weight: 500`.
2. Compare the rendered font with the expected one from a design guideline.

### Rendered page:
![Screen Shot 2021-07-26 at 12 34 05 PM](https://user-images.githubusercontent.com/6138182/127048197-0738c35c-bebe-4e40-a232-d777bc6c39a6.jpg)

### Figma design document:
![Screen Shot 2021-07-26 at 12 35 10 PM](https://user-images.githubusercontent.com/6138182/127048187-59a4957a-08db-467a-b864-1394f2c77b8b.jpg)

## Additional context
The web inspector will show the correct weight (500) without warnings or errors, but if the actual file is not loaded, the browser is actually falling back to the 400-weight font file which is loading correctly. You can verify this by manually swapping out the weight in the inspector with 400 to see that it does not actually change.

In `webcorestylesheets/dist/_fonts.scss`, there are three `@font-face` declarations, but the first two declarations use the same font files for `src`; I am unsure if this is related or not.

**Comment by blackfalcon** [comment]
@MattSidor so here is what I know. There are literally only three weights, 500, 300, and 100. The default weight is 500. 300 and 100 get lighter. 

So when you say that you replaced 500 with 400, what you are seeing is expected because 400 has no value and shows the default 500 weight. 

Regarding the dual use of the one font family, that is because we are actually only using two families. ASCircularWeb-Light and ASCircularWeb-Medium. 

What I am realizing is that this trick to call ASCircularWeb-Light a 300 weight font is pretty much a lie. Most of the thinness is disguised by the size of the type. 

There is also an ongoing discussion with the design team regarding the actual reality of type use and the design system. 

I am going to close this issue as there is nothing to fix because what is coded is working as expected. But that being said, there is additional effort into revising the type ladder and pushing other changes.
